name: QEMU with VirGL

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev libglib2.0-dev libpixman-1-dev git ninja-build libvirglrenderer-dev
        
    - name: Clone QEMU repository
      run: git clone --branch master --depth 1 https://git.qemu.org/git/qemu.git
      
    - name: Configure and compile QEMU with VirGL support
      run: |
        cd qemu
        ./configure --target-list=x86_64-softmmu --enable-virglrenderer
        make -j$(nproc)
        
    - name: Create Release
      id: create_release
      run: |
        RELEASE_NOTES=$(cat <<EOF
        Description of the release
        EOF
        )
        curl \
          --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/releases \
          --header 'authorization: Bearer ${{ secrets.QEMU_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "tag_name": "v1.0",
            "name": "Qemu-VirGL v1.0",
            "body": "$RELEASE_NOTES",
            "draft": false,
            "prerelease": false
          }'

    - name: Upload Release Asset
      run: |
        curl \
          --request POST \
          --url "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=qemu_binary" \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header 'content-type: application/octet-stream' \
          --data-binary @/path/to/qemu_binary
          
